# Generated by Django 3.2.13 on 2024-08-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='動画'),
        ),
    ]
