# Generated by Django 3.2.13 on 2024-08-13 00:32

import base.models.item_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to=base.models.item_models.upload_movie_to, verbose_name='動画'),
        ),
    ]
